---
the-stack-name: &the-stack-name opensuse42

the-bundles: &the-bundles
  'buildpack/opensuse42': "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  'buildpack/cfsle15fs':  "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  'buildpack/cflinuxfs2': "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  'buildpack/cflinuxfs3': "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  docker:                 "docker_app_lifecycle/docker_app_lifecycle.tgz"

the-stacks: &the-stacks
  - name: cflinuxfs2
    description: "Cloud Foundry Linux-based filesystem"
  - name: cflinuxfs3
    description: "Cloud Foundry Linux-based filesystem"
  - name: opensuse42
    description: "openSUSE-based filesystem"
  - name: cfsle15fs
    description: "SUSE SLE-based filesystem"

the-rootfses: &the-rootfses
  - "opensuse42:/var/vcap/packages/opensuse42/rootfs.tar"
  - "cfsle15fs:/var/vcap/packages/cfsle15fs/rootfs.tar"
  - "cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs.tar"
  - "cflinuxfs3:/var/vcap/packages/cflinuxfs3/rootfs.tar"  

the-images: &the-images
  - "/var/vcap/packages/opensuse42/rootfs.tar"
  - "/var/vcap/packages/cfsle15fs/rootfs.tar"
  - "/var/vcap/packages/cflinuxfs2/rootfs.tar"
  - "/var/vcap/packages/cflinuxfs3/rootfs.tar"

# Append common parts here
