---
the-stack-name: &the-stack-name sle12

the-bundles: &the-bundles
  'buildpack/sle12':      "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  'buildpack/cflinuxfs2': "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  'buildpack/cflinuxfs3': "buildpack_app_lifecycle/buildpack_app_lifecycle.tgz"
  docker:                 "docker_app_lifecycle/docker_app_lifecycle.tgz"

the-stacks: &the-stacks
  - name: "cflinuxfs2"
    description: "Cloud Foundry Linux-based filesystem"
  - name: "cflinuxfs3"
    description: "Cloud Foundry Linux-based filesystem"
  - name: "sle12"
    description: "SLE-based filesystem"

the-rootfses: &the-rootfses
  - "sle12:/var/vcap/packages/cf-sle12/rootfs.tar"
  - "cflinuxfs2:/var/vcap/packages/cflinuxfs2/rootfs.tar"
  - "cflinuxfs3:/var/vcap/packages/cflinuxfs3/rootfs.tar"

the-images: &the-images
  - "/var/vcap/packages/cf-sle12/rootfs.tar"
  - "/var/vcap/packages/cflinuxfs2/rootfs.tar"
  - "/var/vcap/packages/cflinuxfs3/rootfs.tar"
# Append common parts here
