---
properties:
  cc:
    droplets:
      droplet_directory_key: the_key
    buildpacks:
      buildpack_directory_key: bd_key
    staging_upload_user: username
    staging_upload_password: password
    bulk_api_password: password
    db_encryption_key: the_key
  ccdb:
    roles:
    - name: ccadmin
      password: admin_password
      tag: admin
  cf-usb:
    broker:
      username: cf-usb_username
      password: cf-usb_password
    management:
      uaa:
        secret: cf-usb_secret
  domain: example.com
  nats:
    user: nats_user
    password: nats_password
  router:
    ssl_cert: ''
    ssl_key: ''
    status:
      user: router_user
      password: router_password
    route_services_secret: null
  smoke_tests:
    api: api.((DOMAIN))
    apps_domain: [ ((DOMAIN)) ]
    user: ((CLUSTER_ADMIN_USERNAME))
    password: ((CLUSTER_ADMIN_PASSWORD))
  uaa:
    admin:
      client_secret: admin_secret
    batch:
      username: batch_username
      password: batch_password
    cc:
      client_secret: cc_client_secret
    clients:
      app-direct:
        secret: app-direct_secret
      cf-usb:
        secret: cf-usb_secret
      cc_routing:
        secret: cc_routing_secret
      cc-service-dashboards:
        secret: cc-broker-secret
      developer_console:
        secret: developer_console_secret
      notifications:
        secret: notification_secret
      tcp_emitter:
         secret: tcp-emitter-secret
      tcp_router:
        secret: tcp-router-secret
      login:
        secret: login_client_secret
      doppler:
        secret: doppler_secret
      cloud_controller_username_lookup:
        secret: cloud_controller_username_lookup_secret
      gorouter:
        secret: gorouter_secret
      ssh-proxy:
        secret: ssh-proxy_secret
    jwt:
      verification_key: vk
      signing_key: sk
    scim:
      users: []      
  uaadb:
    roles:
    - name: uaaadmin
      password: admin_password
      tag: admin
