---
container-networking/v0-14-0-network-policy-plugin-linux64:
  object_id: v0-14-0-network-policy-plugin-linux64
  sha: df087aee2480e2ec67a6b0433fddd351b9f2cc21
  size: 8472248
cli/cf-cli_6.42.0_linux_x86-64.tgz:
  object_id: cf-cli_6.42.0_linux_x86-64.tgz
  sha: 8cde11d372b6a022c101e78df1a563cd5d034269
  size: 7361332
golang/go1.10.linux-amd64.tar.gz:
  size: 119905205
  object_id: go1.10.linux-amd64.tar.gz
  sha: 693e2dfd99ef2d608b41c450efd9d277bf2a7f2f
ruby-2.3/bundler-1.11.2.gem:
  object_id: bundler-1.11.2.gem
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
  size: 263168
ruby-2.3/ruby-2.3.1.tar.gz:
  object_id: ruby-2.3.1.tar.gz
  sha: c39b4001f7acb4e334cb60a0f4df72d434bef711
  size: 17797997
ruby-2.3/rubygems-2.6.4.tgz:
  object_id: rubygems-2.6.4.tgz
  sha: 8ef39e536af2ecd20b0e7a95765fa6a485087ac8
  size: 478582
